export interface Certificate {
  id: string;
  title: string;
  issuer: string;
  period: string;
  credentialId: string;
  filename: string;
  tags: string;
  icon: string;
  iconColor: string;
  credentialUrl?: string;
  delay?: number;
}

export const certificates: Certificate[] = [
  {
    id: '1',
    title: 'Belajar Dasar Pemrograman JavaScript',
    issuer: 'Dicoding',
    period: 'Apr 2025 - Apr 2028',
    credentialId: '98XWEJ88LXM3',
    filename: 'Belajar Dasar Pemrograman JavaScript.pdf',
    tags: 'prog',
    icon: 'CodeXml',
    iconColor: 'purple',
    credentialUrl: 'https://www.dicoding.com/certificates/98XWEJ88LXM3',
  },
  {
    id: '2',
    title: 'Memulai Pemrograman dengan Python',
    issuer: 'Dicoding',
    period: 'Feb 2025 - Feb 2028',
    credentialId: 'NVP757G54XR0',
    filename: 'Memulai Pemrograman dengan Python.pdf',
    tags: 'prog',
    icon: 'Terminal',
    iconColor: 'yellow',
    credentialUrl: 'https://www.dicoding.com/certificates/NVP757G54XR0',
    delay: 50,
  },
  {
    id: '3',
    title: 'Belajar Dasar SQL',
    issuer: 'Dicoding',
    period: 'Feb 2025 - Feb 2028',
    credentialId: 'KEXL78ER4XG2',
    filename: 'Belajar Dasar Structured Query Language (SQL).pdf',
    tags: 'prog',
    icon: 'Database',
    iconColor: 'blue',
    credentialUrl: 'https://www.dicoding.com/certificates/KEXL78ER4XG2',
    delay: 100,
  },
  {
    id: '4',
    title: 'Belajar Dasar Data Science',
    issuer: 'Dicoding',
    period: 'Feb 2025 - Feb 2028',
    credentialId: '53XEDYL5YPRN',
    filename: 'Belajar Dasar Data Science.pdf',
    tags: 'data',
    icon: 'LineChart',
    iconColor: 'brand',
    credentialUrl: 'https://www.dicoding.com/certificates/53XEDYL5YPRN',
  },
  {
    id: '5',
    title: 'Belajar Dasar AI',
    issuer: 'Dicoding',
    period: 'Feb 2025 - Feb 2028',
    credentialId: 'N9ZO9O396XG5',
    filename: 'Belajar Dasar AI.pdf',
    tags: 'aiml',
    icon: 'Sparkles',
    iconColor: 'pink',
    credentialUrl: 'https://www.dicoding.com/certificates/N9ZO9O396XG5',
    delay: 50,
  },
  {
    id: '6',
    title: 'Magang & Studi Independen Bersertifikat',
    issuer: 'Kampus Merdeka',
    period: 'Issued Jul 2024',
    credentialId: 'MSIB-BATCH-6',
    filename: 'msib_kampus_merdeka.pdf',
    tags: 'specialization',
    icon: 'GraduationCap',
    iconColor: 'emerald',
    credentialUrl: 'https://kampusmerdeka.kemdikbud.go.id/',
    delay: 100,
  },
  {
    id: '7',
    title: 'Natural Language Processing Specialization',
    issuer: 'DeepLearning.AI',
    period: 'Jul 2024',
    credentialId: 'C28XKXGK7L5N',
    filename: 'Natural Language Processing Specialization.pdf',
    tags: 'aiml,specialization',
    icon: 'Brain',
    iconColor: 'red',
    credentialUrl: 'https://coursera.org/verify/specialization/C28XKXGK7L5N',
  },
  {
    id: '8',
    title: 'Google Data Analytics Specialization',
    issuer: 'Google',
    period: 'Jul 2024',
    credentialId: 'LBYNLYYC4P8J',
    filename: 'Google Data Analytics Specialization.pdf',
    tags: 'data,specialization',
    icon: 'BarChart3',
    iconColor: 'indigo',
    credentialUrl: 'https://coursera.org/verify/specialization/LBYNLYYC4P8J',
    delay: 50,
  },
  {
    id: '9',
    title: 'Google IT Automation with Python Specialization',
    issuer: 'Google',
    period: 'Jul 2024',
    credentialId: 'T3NC5XFE25EQ',
    filename: 'Google IT Automation with Python Specialization.pdf',
    tags: 'data,specialization',
    icon: 'Cog',
    iconColor: 'amber',
    credentialUrl: 'https://coursera.org/verify/specialization/T3NC5XFE25EQ',
    delay: 100,
  },
  {
    id: '10',
    title: 'TensorFlow: Advanced Techniques Specialization',
    issuer: 'DeepLearning.AI',
    period: 'May 2024',
    credentialId: 'F4SWWCLHVVK6',
    filename: 'TensorFlow Advanced Techniques Specialization.pdf',
    tags: 'aiml,specialization',
    icon: 'Cpu',
    iconColor: 'orange',
    credentialUrl: 'https://coursera.org/verify/specialization/F4SWWCLHVVK6',
  },
  {
    id: '11',
    title: 'TensorFlow: Data and Deployment Specialization',
    issuer: 'DeepLearning.AI',
    period: 'May 2024',
    credentialId: 'ET5D7375S4VS',
    filename: 'TensorFlow Data and Deployment Specialization.pdf',
    tags: 'aiml,specialization',
    icon: 'CloudLightning',
    iconColor: 'orange',
    credentialUrl: 'https://coursera.org/verify/specialization/ET5D7375S4VS',
    delay: 50,
  },
  {
    id: '12',
    title: 'DeepLearning.AI TensorFlow Developer Specialization',
    issuer: 'DeepLearning.AI',
    period: 'Apr 2024',
    credentialId: 'S4EQNAWX6U38',
    filename: 'DeepLearning.AI TensorFlow Developer Specialization.pdf',
    tags: 'aiml,specialization',
    icon: 'Cpu',
    iconColor: 'orange',
    credentialUrl: 'https://coursera.org/verify/specialization/S4EQNAWX6U38',
    delay: 100,
  },
  {
    id: '13',
    title: 'Machine Learning Specialization',
    issuer: 'Stanford University',
    period: 'Mar 2024',
    credentialId: 'UXRQ2YXAUHPX',
    filename: 'Machine Learning Specialization.pdf',
    tags: 'aiml,specialization',
    icon: 'Brain',
    iconColor: 'red',
    credentialUrl: 'https://coursera.org/verify/specialization/UXRQ2YXAUHPX',
  },
  {
    id: '14',
    title: 'Mathematics for ML & Data Science Specialization',
    issuer: 'DeepLearning.AI',
    period: 'Mar 2024',
    credentialId: 'ZGXM7CADA9XE',
    filename: 'Mathematics for ML & Data Science Specialization.pdf',
    tags: 'aiml,specialization',
    icon: 'Calculator',
    iconColor: 'indigo',
    credentialUrl: 'https://coursera.org/verify/specialization/ZGXM7CADA9XE',
    delay: 50,
  },
  {
    id: '15',
    title: 'Belajar Analisis Data dengan Python',
    issuer: 'Dicoding',
    period: 'Mar 2024 - Mar 2027',
    credentialId: 'EYX40L3ERPDL',
    filename: 'Belajar Analisis Data dengan Python.pdf',
    tags: 'data',
    icon: 'LineChart',
    iconColor: 'brand',
    credentialUrl: 'https://www.dicoding.com/certificates/EYX40L3ERPDL',
    delay: 100,
  },
];
